# Generated by Django 4.2.5 on 2023-09-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Amount', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Category', models.TextField()),
                ('Publisher', models.TextField()),
                ('Description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
